// Generated by shared/display_core/tools/gen_font.py — do not edit.
// Source: PixelOperator.ttf @ 16 px (ascent 13, descent 3), ASCII + Latin-1.
#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const uint8_t u8g2_font_hexa_text_16[];

#ifdef __cplusplus
}
#endif
