#!/usr/bin/env python3
"""Generate the u8g2 text font for the hexapod display from Pixel Operator.

Renders each wanted glyph (ASCII + Latin-1) from the vendored
`fonts/PixelOperator.ttf` (CC0, https://www.dafont.com/pixel-operator.font)
with Pillow, writes an intermediate BDF, and runs u8g2's `bdfconv` to produce
the compressed u8g2 font array. Pixel Operator is a true pixel font with a
16 px native em, so rendering at PIXEL_SIZE 16 thresholds pixel-perfectly.

Output is checked in as `shared/display_core/fonts/hexa_text_font.{c,h}` —
regeneration is only needed to change the font, the pixel size, or the
character set.

Requirements (host, not the sim container):
  - Pillow (`python -m pip install pillow` or distro package)
  - `bdfconv`, built from the u8g2 repo:
        git clone --filter=blob:none --sparse https://github.com/olikraus/u8g2
        cd u8g2 && git sparse-checkout set tools/font/bdfconv
        cd tools/font/bdfconv && gcc -O2 -o bdfconv bdf_8x8.c bdf_font.c \
            bdf_glyph.c bdf_kern.c bdf_map.c bdf_parser.c bdf_rle.c \
            bdf_tga.c fd.c main.c

Usage:
  ./gen_font.py --bdfconv /path/to/bdfconv
"""

import argparse
import pathlib
import subprocess
import sys
import tempfile

from PIL import Image, ImageDraw, ImageFont

FONTS_DIR = pathlib.Path(__file__).resolve().parent.parent / "fonts"
DEFAULT_TTF = FONTS_DIR / "PixelOperator.ttf"
FONT_NAME = "u8g2_font_hexa_text_16"
PIXEL_SIZE = 16  # Pixel Operator's native em — render only at multiples of it
THRESHOLD = 128  # grayscale cutoff for the 1-bit OLED bitmap


def codepoints():
    cps = list(range(0x20, 0x7F))          # ASCII
    cps += list(range(0xA0, 0x100))        # Latin-1 supplement (ä ö å ° é …)
    return cps


def render_glyph(font, ascent, cp, threshold):
    """Render one codepoint; return (bitmap rows, BBX, advance)."""
    ch = chr(cp)
    adv = round(font.getlength(ch))
    pad = 8
    img = Image.new("L", (4 * PIXEL_SIZE + 2 * pad, 4 * PIXEL_SIZE), 0)
    ImageDraw.Draw(img).text((pad, 0), ch, font=font, fill=255)
    bw = img.point(lambda v: 255 if v >= threshold else 0)
    box = bw.getbbox()
    if box is None:
        return ([], (0, 0, 0, 0), adv)  # blank glyph (e.g. space)
    x0, y0, x1, y1 = box
    w, h = x1 - x0, y1 - y0
    rows = []
    px = bw.load()
    for y in range(y0, y1):
        bits = 0
        nbytes = (w + 7) // 8
        for x in range(x0, x1):
            bits = (bits << 1) | (1 if px[x, y] else 0)
        bits <<= nbytes * 8 - w  # pad to byte boundary, MSB first
        rows.append(bits.to_bytes(nbytes, "big").hex().upper())
    # BDF: offsets relative to the baseline (Pillow's origin is the line top,
    # baseline at y == ascent).
    return (rows, (w, h, x0 - pad, ascent - y1), adv)


def tofu_bitmap(font, ascent, threshold):
    """The .notdef bitmap, for detecting codepoints missing from the cmap."""
    rows, _, _ = render_glyph(font, ascent, 0xFFFF, threshold)
    return rows


def write_bdf(path, font, threshold):
    ascent, descent = font.getmetrics()
    tofu = tofu_bitmap(font, ascent, threshold)
    glyphs = []
    for cp in codepoints():
        rows, bbx, adv = render_glyph(font, ascent, cp, threshold)
        if cp != 0x20 and (not rows or rows == tofu):
            if cp < 0x80:
                sys.exit(f"error: ASCII U+{cp:04X} ({chr(cp)!r}) missing from font")
            print(f"warning: skipping U+{cp:04X} ({chr(cp)!r}) — not in font")
            continue
        glyphs.append((cp, rows, bbx, adv))

    out = [
        "STARTFONT 2.1",
        f"FONT {FONT_NAME}",
        f"SIZE {PIXEL_SIZE} 75 75",
        f"FONTBOUNDINGBOX {PIXEL_SIZE * 2} {ascent + descent} 0 {-descent}",
        "STARTPROPERTIES 2",
        f"FONT_ASCENT {ascent}",
        f"FONT_DESCENT {descent}",
        "ENDPROPERTIES",
        f"CHARS {len(glyphs)}",
    ]
    for cp, rows, (w, h, xo, yo), adv in glyphs:
        out += [
            f"STARTCHAR U+{cp:04X}",
            f"ENCODING {cp}",
            f"SWIDTH {adv * 1000 // PIXEL_SIZE} 0",
            f"DWIDTH {adv} 0",
            f"BBX {w} {h} {xo} {yo}",
            "BITMAP",
            *rows,
            "ENDCHAR",
        ]
    out.append("ENDFONT")
    path.write_text("\n".join(out) + "\n")
    return ascent, descent


def write_header(path, ttf, ascent, descent):
    lines = [
        "// Generated by shared/display_core/tools/gen_font.py — do not edit.",
        f"// Source: {pathlib.Path(ttf).name} @ {PIXEL_SIZE} px "
        f"(ascent {ascent}, descent {descent}), ASCII + Latin-1.",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        f"extern const uint8_t {FONT_NAME}[];",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
    ]
    path.write_text("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--ttf", default=str(DEFAULT_TTF))
    ap.add_argument("--bdfconv", default="bdfconv")
    ap.add_argument("--threshold", type=int, default=THRESHOLD)
    args = ap.parse_args()

    FONTS_DIR.mkdir(exist_ok=True)
    font = ImageFont.truetype(args.ttf, PIXEL_SIZE)

    with tempfile.TemporaryDirectory() as tmp:
        bdf = pathlib.Path(tmp) / "font.bdf"
        raw = pathlib.Path(tmp) / "font.c"
        ascent, descent = write_bdf(bdf, font, args.threshold)
        subprocess.run(
            [args.bdfconv, "-v", "-b", "0", "-f", "1", "-m", "32-255",
             str(bdf), "-o", str(raw), "-n", FONT_NAME],
            check=True, capture_output=True, text=True)
        body = raw.read_text()

    c_path = FONTS_DIR / "hexa_text_font.c"
    c_path.write_text(
        "// Generated by shared/display_core/tools/gen_font.py — do not edit.\n"
        f"// Source: {pathlib.Path(args.ttf).name} @ {PIXEL_SIZE} px, "
        f"threshold {args.threshold}.\n"
        '#include "u8g2.h"\n\n' + body)
    write_header(FONTS_DIR / "hexa_text_font.h", args.ttf, ascent, descent)
    print(f"wrote {c_path} ({len(c_path.read_bytes())} bytes source)")


if __name__ == "__main__":
    main()
